# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  epochs: 200
  iters_per_epoch: &iters_per_epoch 50
  save_freq: 10
  log_freq: 20
  eval_during_train: True
  eval_freq: 1
  use_visualdl: False
  save_inference_dir: ./inference
  # to_static: False

Geometry:
  - TimeXGeometry:
      name: &geom_name time_rect
      TimeDomain:
        t0: 0.0
        t1: 0.5
        time_step: 0.1
      Rectangle:
        xmin: [-0.05, -0.05]
        xmax: [0.05, 0.05]

Arch:
  name: MLP
  input_keys: ["t", "x", "y"]
  output_keys: ["u", "v", "p"]
  num_layers: 9
  hidden_size: 50
  activation: tanh

Optimizer:
  name: Adam
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 6

# AMP:
#   init_loss_scaling: 65536
#   use_dynamic_loss_scaling: True
#   level: O1

Equation:
  - NavierStokes:
      nu: 0.01
      rho: 1.0
      dim: 2
      time: True

Constraint:
  dataloader:
    iters_per_epoch: *iters_per_epoch
    shuffle: True
    drop_last: False
    num_workers: 0
    seed: 42
    use_shared_memory: False
  content:
    - InteriorConstraint:
        name: EQ
        label_expr: NavierStokes
        label_dict: { "continuity": 0, "momentum_x": 0, "momentum_y": 0 }
        geom: *geom_name
        dataloader:
          batch_size: 51200
        loss:
          name: MSELoss
          reduction: sum
        weight_dict:
          { "continuity": 1.0e-4, "momentum_x": 1.0e-4, "momentum_y": 1.0e-4 }
    - BoundaryConstraint:
        name: BC_top
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 1, "v": 0 }
        geom: *geom_name
        criteria: "lambda t, x, y: np.isclose(y, 0.05)"
        dataloader:
          batch_size: 512
        loss:
          name: MSELoss
          reduction: sum
        weight_dict: { "u": "1-20*abs(x)" }
    - BoundaryConstraint:
        name: BC_down
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: *geom_name
        criteria: "lambda t, x, y: np.isclose(y, -0.05)"
        dataloader:
          batch_size: 512
        loss:
          name: MSELoss
          reduction: sum
    - BoundaryConstraint:
        name: BC_left
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: *geom_name
        criteria: "lambda t, x, y: np.isclose(x, -0.05)"
        dataloader:
          batch_size: 512
        loss:
          name: MSELoss
          reduction: sum
    - BoundaryConstraint:
        name: BC_right
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: *geom_name
        criteria: "lambda t, x, y: np.isclose(x, 0.05)"
        dataloader:
          batch_size: 512
        loss:
          name: MSELoss
          reduction: sum
    - InitialConstraint:
        name: IC
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: *geom_name
        dataloader:
          batch_size: 10240
        loss:
          name: MSELoss
          reduction: sum

Validator:
  dataloader:
    shuffle: False
    drop_last: False
    num_workers: 0
    seed: 42
    use_shared_memory: False
  content:
    - NumpyValidator:
        name: Residual
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: *geom_name
        dataloader:
          total_size: 6144
          batch_size: 1024
        loss:
          name: MSELoss
          reduction: mean
        evenly: True
        metric:
          - MSE: {}
        with_initial: True

# Infer: TODO...
