# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  epochs: 200
  iters_per_epoch: &iters_per_epoch 100
  save_freq: 10
  log_freq: 20
  eval_during_train: True
  eval_freq: 1
  use_visualdl: False
  save_inference_dir: ./inference
  # to_static: False

Geometry:
  - Rectangle:
      name: rect
      xmin: [-0.05, -0.05]
      xmax: [0.05, 0.05]

Arch:
  name: MLP
  input_keys: ["x", "y"]
  output_keys: ["u", "v", "p"]
  num_layers: 9
  hidden_size: 50
  activation: tanh

Equation:
  - NavierStokes:
      nu: 0.01
      rho: 1.0
      dim: 2
      time: False

Constraint:
  dataloader:
    iters_per_epoch: *iters_per_epoch
    shuffle: True
    drop_last: False
    num_workers: 0
    seed: 42
    use_shared_memory: False
  content:
    - InteriorConstraint:
        name: EQ
        label_expr: NavierStokes
        label_dict: { "continuity": 0, "momentum_x": 0, "momentum_y": 0 }
        geom: rect
        dataloader:
          batch_size: 9801
        loss:
          name: MSELoss
          reduction: sum
        weight_dict:
          { "continuity": 1.0e-4, "momentum_x": 1.0e-4, "momentum_y": 1.0e-4 }
    - BoundaryConstraint:
        name: BC_top
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 1, "v": 0 }
        geom: rect
        criteria: "lambda x, y: np.isclose(y, 0.05)"
        dataloader:
          batch_size: 101
        loss:
          name: MSELoss
          reduction: sum
        weight_dict: { "u": "1-20*abs(x)" }
    - BoundaryConstraint:
        name: BC_down
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: rect
        criteria: "lambda x, y: np.isclose(y, -0.05)"
        dataloader:
          batch_size: 101
        loss:
          name: MSELoss
          reduction: sum
    - BoundaryConstraint:
        name: BC_left
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: rect
        criteria: "lambda x, y: np.isclose(x, -0.05)"
        dataloader:
          batch_size: 99
        loss:
          name: MSELoss
          reduction: sum
    - BoundaryConstraint:
        name: BC_right
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: rect
        criteria: "lambda x, y: np.isclose(x, 0.05)"
        dataloader:
          batch_size: 99
        loss:
          name: MSELoss
          reduction: sum

Validator:
  dataloader:
    shuffle: False
    drop_last: False
    num_workers: 0
    seed: 42
    use_shared_memory: False
  content:
    - NumpyValidator:
        name: Residual
        label_expr: { "u": "u", "v": "v" }
        label_dict: { "u": 0, "v": 0 }
        geom: rect
        dataloader:
          total_size: 12001
          batch_size: 12001
        loss:
          name: MSELoss
          reduction: mean
        metric:
          - MSE: {}

# AMP:
#   init_loss_scaling: 65536
#   use_dynamic_loss_scaling: True
#   level: O2

Optimizer:
  name: Adam
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 6

# Infer: TODO...
